use_frameworks!

platform :ios, '14.0'

target 'Keychainer_Example' do
  pod 'Keychainer', :path => '../'

  target 'Keychainer_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 6.1.0'
    pod 'Nimble', '~> 11.2.1'
  end
end
