use_frameworks!

platform :ios, '14.0'

target 'Keychainer_Example' do
  pod 'Keychainer', :path => '../'

  target 'Keychainer_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.2.0'
    pod 'Nimble', '~> 8.0.7'
  end
end
